// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrendEmber.Data;

#nullable disable

namespace TrendEmber.Data.Migrations.TrendsDb
{
    [DbContext(typeof(TrendsDbContext))]
    [Migration("20250227201159_AddHarvesterRunFunctionality")]
    partial class AddHarvesterRunFunctionality
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrendEmber.Core.Trends.ApiProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApiProviders");
                });

            modelBuilder.Entity("TrendEmber.Core.Trends.HarvesterAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApiProviderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiProviderId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("TrendEmber.Core.Trends.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BasedOn")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Entry")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("StopLoss")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TG1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TG2")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TradeSetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TradeSetId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("TrendEmber.Core.Trends.TradeSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ImportedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TradeSets");
                });

            modelBuilder.Entity("TrendEmber.Core.Trends.WatchList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HarvesterAgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ImportedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HarvesterAgentId")
                        .IsUnique();

                    b.ToTable("WatchList");
                });

            modelBuilder.Entity("TrendEmber.Core.Trends.WatchListSymbol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastImportedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WatchListId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WatchListId");

                    b.ToTable("Symbols");
                });

            modelBuilder.Entity("TrendEmber.Core.Trends.HarvesterAgent", b =>
                {
                    b.HasOne("TrendEmber.Core.Trends.ApiProvider", "ApiProvider")
                        .WithMany("Agents")
                        .HasForeignKey("ApiProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiProvider");
                });

            modelBuilder.Entity("TrendEmber.Core.Trends.Trade", b =>
                {
                    b.HasOne("TrendEmber.Core.Trends.TradeSet", "TradeSet")
                        .WithMany("Trades")
                        .HasForeignKey("TradeSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeSet");
                });

            modelBuilder.Entity("TrendEmber.Core.Trends.WatchList", b =>
                {
                    b.HasOne("TrendEmber.Core.Trends.HarvesterAgent", "Agent")
                        .WithOne("WatchList")
                        .HasForeignKey("TrendEmber.Core.Trends.WatchList", "HarvesterAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("TrendEmber.Core.Trends.WatchListSymbol", b =>
                {
                    b.HasOne("TrendEmber.Core.Trends.WatchList", "WatchList")
                        .WithMany("Symbols")
                        .HasForeignKey("WatchListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WatchList");
                });

            modelBuilder.Entity("TrendEmber.Core.Trends.ApiProvider", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("TrendEmber.Core.Trends.HarvesterAgent", b =>
                {
                    b.Navigation("WatchList")
                        .IsRequired();
                });

            modelBuilder.Entity("TrendEmber.Core.Trends.TradeSet", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("TrendEmber.Core.Trends.WatchList", b =>
                {
                    b.Navigation("Symbols");
                });
#pragma warning restore 612, 618
        }
    }
}
